trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# 1) Install .NET SDK 8.x
- task: UseDotNet@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    packageType: sdk
    version: '8.x'            # Picks up latest 8.0 SDK
    includePreview: false     # set to true if you need preview bits

# 2) Restore dependencies
- script: dotnet restore
  displayName: 'dotnet restore'

# 3) Build
- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'dotnet build'

# 4) Test (remove if you have no tests)
- script: dotnet test --configuration $(buildConfiguration) --no-build
  displayName: 'dotnet test'

# 5) Publish
- script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet publish'

# 6) Publish artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
